// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.3
// source: proto/paxos.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_REQUEST  MessageType = 0
	MessageType_RESPONSE MessageType = 1
	MessageType_ACCEPT   MessageType = 2
	MessageType_ACCEPTED MessageType = 3
	MessageType_COMMIT   MessageType = 4
	MessageType_COMMITED MessageType = 5
	MessageType_EXECUTE  MessageType = 6
	MessageType_EXECUTED MessageType = 7
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "REQUEST",
		1: "RESPONSE",
		2: "ACCEPT",
		3: "ACCEPTED",
		4: "COMMIT",
		5: "COMMITED",
		6: "EXECUTE",
		7: "EXECUTED",
	}
	MessageType_value = map[string]int32{
		"REQUEST":  0,
		"RESPONSE": 1,
		"ACCEPT":   2,
		"ACCEPTED": 3,
		"COMMIT":   4,
		"COMMITED": 5,
		"EXECUTE":  6,
		"EXECUTED": 7,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_paxos_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_paxos_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{0}
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Reciever      string                 `protobuf:"bytes,2,opt,name=reciever,proto3" json:"reciever,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_paxos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Transaction) GetReciever() string {
	if x != nil {
		return x.Reciever
	}
	return ""
}

func (x *Transaction) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type BallotNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TermNo        int32                  `protobuf:"varint,1,opt,name=term_no,json=termNo,proto3" json:"term_no,omitempty"`
	NodeNo        int32                  `protobuf:"varint,2,opt,name=node_no,json=nodeNo,proto3" json:"node_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BallotNumber) Reset() {
	*x = BallotNumber{}
	mi := &file_proto_paxos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BallotNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BallotNumber) ProtoMessage() {}

func (x *BallotNumber) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BallotNumber.ProtoReflect.Descriptor instead.
func (*BallotNumber) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{1}
}

func (x *BallotNumber) GetTermNo() int32 {
	if x != nil {
		return x.TermNo
	}
	return 0
}

func (x *BallotNumber) GetNodeNo() int32 {
	if x != nil {
		return x.NodeNo
	}
	return 0
}

type ClientRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageType   MessageType            `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=banking.MessageType" json:"message_type,omitempty"`
	Time          int32                  `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Transaction   *Transaction           `protobuf:"bytes,3,opt,name=transaction,proto3" json:"transaction,omitempty"`
	ClientNumber  string                 `protobuf:"bytes,4,opt,name=client_number,json=clientNumber,proto3" json:"client_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRequestMessage) Reset() {
	*x = ClientRequestMessage{}
	mi := &file_proto_paxos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequestMessage) ProtoMessage() {}

func (x *ClientRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequestMessage.ProtoReflect.Descriptor instead.
func (*ClientRequestMessage) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{2}
}

func (x *ClientRequestMessage) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_REQUEST
}

func (x *ClientRequestMessage) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *ClientRequestMessage) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *ClientRequestMessage) GetClientNumber() string {
	if x != nil {
		return x.ClientNumber
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsExecuted    bool                   `protobuf:"varint,1,opt,name=is_executed,json=isExecuted,proto3" json:"is_executed,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"` // for read only transaction
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_proto_paxos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{3}
}

func (x *Result) GetIsExecuted() bool {
	if x != nil {
		return x.IsExecuted
	}
	return false
}

func (x *Result) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ClientResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageType   MessageType            `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=banking.MessageType" json:"message_type,omitempty"`
	BallotNo      *BallotNumber          `protobuf:"bytes,2,opt,name=ballot_no,json=ballotNo,proto3" json:"ballot_no,omitempty"`
	Time          int32                  `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	ClientNumber  string                 `protobuf:"bytes,4,opt,name=client_number,json=clientNumber,proto3" json:"client_number,omitempty"`
	Result        bool                   `protobuf:"varint,5,opt,name=result,proto3" json:"result,omitempty"`
	ResultStruct  *Result                `protobuf:"bytes,6,opt,name=result_struct,json=resultStruct,proto3" json:"result_struct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientResponseMessage) Reset() {
	*x = ClientResponseMessage{}
	mi := &file_proto_paxos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientResponseMessage) ProtoMessage() {}

func (x *ClientResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientResponseMessage.ProtoReflect.Descriptor instead.
func (*ClientResponseMessage) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{4}
}

func (x *ClientResponseMessage) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_REQUEST
}

func (x *ClientResponseMessage) GetBallotNo() *BallotNumber {
	if x != nil {
		return x.BallotNo
	}
	return nil
}

func (x *ClientResponseMessage) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *ClientResponseMessage) GetClientNumber() string {
	if x != nil {
		return x.ClientNumber
	}
	return ""
}

func (x *ClientResponseMessage) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *ClientResponseMessage) GetResultStruct() *Result {
	if x != nil {
		return x.ResultStruct
	}
	return nil
}

type AcceptMessageRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MessageType          MessageType            `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=banking.MessageType" json:"message_type,omitempty"`
	BallotNumber         *BallotNumber          `protobuf:"bytes,2,opt,name=ballot_number,json=ballotNumber,proto3" json:"ballot_number,omitempty"`
	SequenceNumber       int32                  `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Transaction          *Transaction           `protobuf:"bytes,4,opt,name=transaction,proto3" json:"transaction,omitempty"`
	ClientRequestMessage *ClientRequestMessage  `protobuf:"bytes,5,opt,name=client_request_message,json=clientRequestMessage,proto3" json:"client_request_message,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AcceptMessageRequest) Reset() {
	*x = AcceptMessageRequest{}
	mi := &file_proto_paxos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptMessageRequest) ProtoMessage() {}

func (x *AcceptMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptMessageRequest.ProtoReflect.Descriptor instead.
func (*AcceptMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{5}
}

func (x *AcceptMessageRequest) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_REQUEST
}

func (x *AcceptMessageRequest) GetBallotNumber() *BallotNumber {
	if x != nil {
		return x.BallotNumber
	}
	return nil
}

func (x *AcceptMessageRequest) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *AcceptMessageRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *AcceptMessageRequest) GetClientRequestMessage() *ClientRequestMessage {
	if x != nil {
		return x.ClientRequestMessage
	}
	return nil
}

type AcceptMessageResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageType    MessageType            `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=banking.MessageType" json:"message_type,omitempty"`
	BallotNumber   *BallotNumber          `protobuf:"bytes,2,opt,name=ballot_number,json=ballotNumber,proto3" json:"ballot_number,omitempty"`
	SequenceNumber int32                  `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Transaction    *Transaction           `protobuf:"bytes,4,opt,name=transaction,proto3" json:"transaction,omitempty"`
	NodeNumber     int32                  `protobuf:"varint,5,opt,name=node_number,json=nodeNumber,proto3" json:"node_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AcceptMessageResponse) Reset() {
	*x = AcceptMessageResponse{}
	mi := &file_proto_paxos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptMessageResponse) ProtoMessage() {}

func (x *AcceptMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptMessageResponse.ProtoReflect.Descriptor instead.
func (*AcceptMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{6}
}

func (x *AcceptMessageResponse) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_REQUEST
}

func (x *AcceptMessageResponse) GetBallotNumber() *BallotNumber {
	if x != nil {
		return x.BallotNumber
	}
	return nil
}

func (x *AcceptMessageResponse) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *AcceptMessageResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *AcceptMessageResponse) GetNodeNumber() int32 {
	if x != nil {
		return x.NodeNumber
	}
	return 0
}

type CommitMessageRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MessageType          MessageType            `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=banking.MessageType" json:"message_type,omitempty"`
	BallotNumber         *BallotNumber          `protobuf:"bytes,2,opt,name=ballot_number,json=ballotNumber,proto3" json:"ballot_number,omitempty"`
	SequenceNumber       int32                  `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Transaction          *Transaction           `protobuf:"bytes,4,opt,name=transaction,proto3" json:"transaction,omitempty"`
	ClientRequestMessage *ClientRequestMessage  `protobuf:"bytes,5,opt,name=client_request_message,json=clientRequestMessage,proto3" json:"client_request_message,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CommitMessageRequest) Reset() {
	*x = CommitMessageRequest{}
	mi := &file_proto_paxos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitMessageRequest) ProtoMessage() {}

func (x *CommitMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitMessageRequest.ProtoReflect.Descriptor instead.
func (*CommitMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{7}
}

func (x *CommitMessageRequest) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_REQUEST
}

func (x *CommitMessageRequest) GetBallotNumber() *BallotNumber {
	if x != nil {
		return x.BallotNumber
	}
	return nil
}

func (x *CommitMessageRequest) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *CommitMessageRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *CommitMessageRequest) GetClientRequestMessage() *ClientRequestMessage {
	if x != nil {
		return x.ClientRequestMessage
	}
	return nil
}

type CommitMessageResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageType    MessageType            `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=banking.MessageType" json:"message_type,omitempty"`
	BallotNumber   *BallotNumber          `protobuf:"bytes,2,opt,name=ballot_number,json=ballotNumber,proto3" json:"ballot_number,omitempty"`
	SequenceNumber int32                  `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommitMessageResponse) Reset() {
	*x = CommitMessageResponse{}
	mi := &file_proto_paxos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitMessageResponse) ProtoMessage() {}

func (x *CommitMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitMessageResponse.ProtoReflect.Descriptor instead.
func (*CommitMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{8}
}

func (x *CommitMessageResponse) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_REQUEST
}

func (x *CommitMessageResponse) GetBallotNumber() *BallotNumber {
	if x != nil {
		return x.BallotNumber
	}
	return nil
}

func (x *CommitMessageResponse) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

type StatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber int32                  `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_paxos_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{9}
}

func (x *StatusRequest) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

type StatusResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	NodeId               int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SequenceNumber       int32                  `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Status               string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ClientRequestMessage *ClientRequestMessage  `protobuf:"bytes,4,opt,name=client_request_message,json=clientRequestMessage,proto3" json:"client_request_message,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_paxos_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{10}
}

func (x *StatusResponse) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *StatusResponse) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusResponse) GetClientRequestMessage() *ClientRequestMessage {
	if x != nil {
		return x.ClientRequestMessage
	}
	return nil
}

type DBRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBRequest) Reset() {
	*x = DBRequest{}
	mi := &file_proto_paxos_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBRequest) ProtoMessage() {}

func (x *DBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBRequest.ProtoReflect.Descriptor instead.
func (*DBRequest) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{11}
}

type DBResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Balances      map[string]int32       `protobuf:"bytes,2,rep,name=balances,proto3" json:"balances,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBResponse) Reset() {
	*x = DBResponse{}
	mi := &file_proto_paxos_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBResponse) ProtoMessage() {}

func (x *DBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBResponse.ProtoReflect.Descriptor instead.
func (*DBResponse) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{12}
}

func (x *DBResponse) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *DBResponse) GetBalances() map[string]int32 {
	if x != nil {
		return x.Balances
	}
	return nil
}

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_proto_paxos_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{13}
}

type LogEntryMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber int32                  `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	BallotNumber   *BallotNumber          `protobuf:"bytes,2,opt,name=ballot_number,json=ballotNumber,proto3" json:"ballot_number,omitempty"`
	ClientRequest  *ClientRequestMessage  `protobuf:"bytes,3,opt,name=client_request,json=clientRequest,proto3" json:"client_request,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LogEntryMessage) Reset() {
	*x = LogEntryMessage{}
	mi := &file_proto_paxos_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntryMessage) ProtoMessage() {}

func (x *LogEntryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntryMessage.ProtoReflect.Descriptor instead.
func (*LogEntryMessage) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{14}
}

func (x *LogEntryMessage) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *LogEntryMessage) GetBallotNumber() *BallotNumber {
	if x != nil {
		return x.BallotNumber
	}
	return nil
}

func (x *LogEntryMessage) GetClientRequest() *ClientRequestMessage {
	if x != nil {
		return x.ClientRequest
	}
	return nil
}

func (x *LogEntryMessage) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Entries       []*LogEntryMessage     `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_proto_paxos_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{15}
}

func (x *LogResponse) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *LogResponse) GetEntries() []*LogEntryMessage {
	if x != nil {
		return x.Entries
	}
	return nil
}

type AcceptLogEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BallotNumber   *BallotNumber          `protobuf:"bytes,1,opt,name=ballot_number,json=ballotNumber,proto3" json:"ballot_number,omitempty"`
	SequenceNumber int32                  `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	AcceptValue    *ClientRequestMessage  `protobuf:"bytes,3,opt,name=accept_value,json=acceptValue,proto3" json:"accept_value,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AcceptLogEntry) Reset() {
	*x = AcceptLogEntry{}
	mi := &file_proto_paxos_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptLogEntry) ProtoMessage() {}

func (x *AcceptLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptLogEntry.ProtoReflect.Descriptor instead.
func (*AcceptLogEntry) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{16}
}

func (x *AcceptLogEntry) GetBallotNumber() *BallotNumber {
	if x != nil {
		return x.BallotNumber
	}
	return nil
}

func (x *AcceptLogEntry) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *AcceptLogEntry) GetAcceptValue() *ClientRequestMessage {
	if x != nil {
		return x.AcceptValue
	}
	return nil
}

func (x *AcceptLogEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PrepareMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BallotNumber  *BallotNumber          `protobuf:"bytes,1,opt,name=ballot_number,json=ballotNumber,proto3" json:"ballot_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareMessage) Reset() {
	*x = PrepareMessage{}
	mi := &file_proto_paxos_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareMessage) ProtoMessage() {}

func (x *PrepareMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareMessage.ProtoReflect.Descriptor instead.
func (*PrepareMessage) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{17}
}

func (x *PrepareMessage) GetBallotNumber() *BallotNumber {
	if x != nil {
		return x.BallotNumber
	}
	return nil
}

type PromiseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BallotNumber  *BallotNumber          `protobuf:"bytes,1,opt,name=ballot_number,json=ballotNumber,proto3" json:"ballot_number,omitempty"`
	AcceptLog     []*AcceptLogEntry      `protobuf:"bytes,2,rep,name=accept_log,json=acceptLog,proto3" json:"accept_log,omitempty"`
	FromNodeId    int32                  `protobuf:"varint,3,opt,name=from_node_id,json=fromNodeId,proto3" json:"from_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromiseMessage) Reset() {
	*x = PromiseMessage{}
	mi := &file_proto_paxos_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromiseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromiseMessage) ProtoMessage() {}

func (x *PromiseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromiseMessage.ProtoReflect.Descriptor instead.
func (*PromiseMessage) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{18}
}

func (x *PromiseMessage) GetBallotNumber() *BallotNumber {
	if x != nil {
		return x.BallotNumber
	}
	return nil
}

func (x *PromiseMessage) GetAcceptLog() []*AcceptLogEntry {
	if x != nil {
		return x.AcceptLog
	}
	return nil
}

func (x *PromiseMessage) GetFromNodeId() int32 {
	if x != nil {
		return x.FromNodeId
	}
	return 0
}

type NewViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BallotNumber  *BallotNumber          `protobuf:"bytes,1,opt,name=ballot_number,json=ballotNumber,proto3" json:"ballot_number,omitempty"`
	AcceptLog     []*AcceptLogEntry      `protobuf:"bytes,2,rep,name=accept_log,json=acceptLog,proto3" json:"accept_log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewViewRequest) Reset() {
	*x = NewViewRequest{}
	mi := &file_proto_paxos_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewViewRequest) ProtoMessage() {}

func (x *NewViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewViewRequest.ProtoReflect.Descriptor instead.
func (*NewViewRequest) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{19}
}

func (x *NewViewRequest) GetBallotNumber() *BallotNumber {
	if x != nil {
		return x.BallotNumber
	}
	return nil
}

func (x *NewViewRequest) GetAcceptLog() []*AcceptLogEntry {
	if x != nil {
		return x.AcceptLog
	}
	return nil
}

type NewViewResponse struct {
	state                 protoimpl.MessageState   `protogen:"open.v1"`
	AcceptMessageResponse []*AcceptMessageResponse `protobuf:"bytes,1,rep,name=accept_message_response,json=acceptMessageResponse,proto3" json:"accept_message_response,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *NewViewResponse) Reset() {
	*x = NewViewResponse{}
	mi := &file_proto_paxos_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewViewResponse) ProtoMessage() {}

func (x *NewViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewViewResponse.ProtoReflect.Descriptor instead.
func (*NewViewResponse) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{20}
}

func (x *NewViewResponse) GetAcceptMessageResponse() []*AcceptMessageResponse {
	if x != nil {
		return x.AcceptMessageResponse
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderId      int32                  `protobuf:"varint,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	BallotNumber  *BallotNumber          `protobuf:"bytes,2,opt,name=ballot_number,json=ballotNumber,proto3" json:"ballot_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_paxos_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{21}
}

func (x *HeartbeatRequest) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *HeartbeatRequest) GetBallotNumber() *BallotNumber {
	if x != nil {
		return x.BallotNumber
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_paxos_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{22}
}

func (x *HeartbeatResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

type AliveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alive         bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	AliveNodes    []int32                `protobuf:"varint,2,rep,packed,name=alive_nodes,json=aliveNodes,proto3" json:"alive_nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AliveRequest) Reset() {
	*x = AliveRequest{}
	mi := &file_proto_paxos_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AliveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliveRequest) ProtoMessage() {}

func (x *AliveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliveRequest.ProtoReflect.Descriptor instead.
func (*AliveRequest) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{23}
}

func (x *AliveRequest) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *AliveRequest) GetAliveNodes() []int32 {
	if x != nil {
		return x.AliveNodes
	}
	return nil
}

type AliveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AliveResponse) Reset() {
	*x = AliveResponse{}
	mi := &file_proto_paxos_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AliveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliveResponse) ProtoMessage() {}

func (x *AliveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliveResponse.ProtoReflect.Descriptor instead.
func (*AliveResponse) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{24}
}

func (x *AliveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PrintViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrintViewRequest) Reset() {
	*x = PrintViewRequest{}
	mi := &file_proto_paxos_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrintViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintViewRequest) ProtoMessage() {}

func (x *PrintViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintViewRequest.ProtoReflect.Descriptor instead.
func (*PrintViewRequest) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{25}
}

type PrintViewResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NewViewRequest []*NewViewRequest      `protobuf:"bytes,1,rep,name=new_view_request,json=newViewRequest,proto3" json:"new_view_request,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrintViewResponse) Reset() {
	*x = PrintViewResponse{}
	mi := &file_proto_paxos_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrintViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintViewResponse) ProtoMessage() {}

func (x *PrintViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintViewResponse.ProtoReflect.Descriptor instead.
func (*PrintViewResponse) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{26}
}

func (x *PrintViewResponse) GetNewViewRequest() []*NewViewRequest {
	if x != nil {
		return x.NewViewRequest
	}
	return nil
}

type FailCurrentLeaderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailCurrentLeaderRequest) Reset() {
	*x = FailCurrentLeaderRequest{}
	mi := &file_proto_paxos_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailCurrentLeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailCurrentLeaderRequest) ProtoMessage() {}

func (x *FailCurrentLeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailCurrentLeaderRequest.ProtoReflect.Descriptor instead.
func (*FailCurrentLeaderRequest) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{27}
}

type FailCurrentLeaderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailCurrentLeaderResponse) Reset() {
	*x = FailCurrentLeaderResponse{}
	mi := &file_proto_paxos_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailCurrentLeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailCurrentLeaderResponse) ProtoMessage() {}

func (x *FailCurrentLeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailCurrentLeaderResponse.ProtoReflect.Descriptor instead.
func (*FailCurrentLeaderResponse) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{28}
}

type PrintLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrintLogRequest) Reset() {
	*x = PrintLogRequest{}
	mi := &file_proto_paxos_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrintLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintLogRequest) ProtoMessage() {}

func (x *PrintLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintLogRequest.ProtoReflect.Descriptor instead.
func (*PrintLogRequest) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{29}
}

type PrintLogResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LogEntryMessage []*LogEntryMessage     `protobuf:"bytes,1,rep,name=log_entry_message,json=logEntryMessage,proto3" json:"log_entry_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PrintLogResponse) Reset() {
	*x = PrintLogResponse{}
	mi := &file_proto_paxos_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrintLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintLogResponse) ProtoMessage() {}

func (x *PrintLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintLogResponse.ProtoReflect.Descriptor instead.
func (*PrintLogResponse) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{30}
}

func (x *PrintLogResponse) GetLogEntryMessage() []*LogEntryMessage {
	if x != nil {
		return x.LogEntryMessage
	}
	return nil
}

type ActiveCatchUpRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AcceptLogEntries []*AcceptLogEntry      `protobuf:"bytes,1,rep,name=accept_log_entries,json=acceptLogEntries,proto3" json:"accept_log_entries,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ActiveCatchUpRequest) Reset() {
	*x = ActiveCatchUpRequest{}
	mi := &file_proto_paxos_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveCatchUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveCatchUpRequest) ProtoMessage() {}

func (x *ActiveCatchUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveCatchUpRequest.ProtoReflect.Descriptor instead.
func (*ActiveCatchUpRequest) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{31}
}

func (x *ActiveCatchUpRequest) GetAcceptLogEntries() []*AcceptLogEntry {
	if x != nil {
		return x.AcceptLogEntries
	}
	return nil
}

type ActiveCatchUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveCatchUpResponse) Reset() {
	*x = ActiveCatchUpResponse{}
	mi := &file_proto_paxos_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveCatchUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveCatchUpResponse) ProtoMessage() {}

func (x *ActiveCatchUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveCatchUpResponse.ProtoReflect.Descriptor instead.
func (*ActiveCatchUpResponse) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{32}
}

var File_proto_paxos_proto protoreflect.FileDescriptor

const file_proto_paxos_proto_rawDesc = "" +
	"\n" +
	"\x11proto/paxos.proto\x12\abanking\x1a\x1bgoogle/protobuf/empty.proto\"Y\n" +
	"\vTransaction\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1a\n" +
	"\breciever\x18\x02 \x01(\tR\breciever\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\"@\n" +
	"\fBallotNumber\x12\x17\n" +
	"\aterm_no\x18\x01 \x01(\x05R\x06termNo\x12\x17\n" +
	"\anode_no\x18\x02 \x01(\x05R\x06nodeNo\"\xc0\x01\n" +
	"\x14ClientRequestMessage\x127\n" +
	"\fmessage_type\x18\x01 \x01(\x0e2\x14.banking.MessageTypeR\vmessageType\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x05R\x04time\x126\n" +
	"\vtransaction\x18\x03 \x01(\v2\x14.banking.TransactionR\vtransaction\x12#\n" +
	"\rclient_number\x18\x04 \x01(\tR\fclientNumber\"?\n" +
	"\x06Result\x12\x1f\n" +
	"\vis_executed\x18\x01 \x01(\bR\n" +
	"isExecuted\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\"\x8b\x02\n" +
	"\x15ClientResponseMessage\x127\n" +
	"\fmessage_type\x18\x01 \x01(\x0e2\x14.banking.MessageTypeR\vmessageType\x122\n" +
	"\tballot_no\x18\x02 \x01(\v2\x15.banking.BallotNumberR\bballotNo\x12\x12\n" +
	"\x04time\x18\x03 \x01(\x05R\x04time\x12#\n" +
	"\rclient_number\x18\x04 \x01(\tR\fclientNumber\x12\x16\n" +
	"\x06result\x18\x05 \x01(\bR\x06result\x124\n" +
	"\rresult_struct\x18\x06 \x01(\v2\x0f.banking.ResultR\fresultStruct\"\xc1\x02\n" +
	"\x14AcceptMessageRequest\x127\n" +
	"\fmessage_type\x18\x01 \x01(\x0e2\x14.banking.MessageTypeR\vmessageType\x12:\n" +
	"\rballot_number\x18\x02 \x01(\v2\x15.banking.BallotNumberR\fballotNumber\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\x05R\x0esequenceNumber\x126\n" +
	"\vtransaction\x18\x04 \x01(\v2\x14.banking.TransactionR\vtransaction\x12S\n" +
	"\x16client_request_message\x18\x05 \x01(\v2\x1d.banking.ClientRequestMessageR\x14clientRequestMessage\"\x8e\x02\n" +
	"\x15AcceptMessageResponse\x127\n" +
	"\fmessage_type\x18\x01 \x01(\x0e2\x14.banking.MessageTypeR\vmessageType\x12:\n" +
	"\rballot_number\x18\x02 \x01(\v2\x15.banking.BallotNumberR\fballotNumber\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\x05R\x0esequenceNumber\x126\n" +
	"\vtransaction\x18\x04 \x01(\v2\x14.banking.TransactionR\vtransaction\x12\x1f\n" +
	"\vnode_number\x18\x05 \x01(\x05R\n" +
	"nodeNumber\"\xc1\x02\n" +
	"\x14CommitMessageRequest\x127\n" +
	"\fmessage_type\x18\x01 \x01(\x0e2\x14.banking.MessageTypeR\vmessageType\x12:\n" +
	"\rballot_number\x18\x02 \x01(\v2\x15.banking.BallotNumberR\fballotNumber\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\x05R\x0esequenceNumber\x126\n" +
	"\vtransaction\x18\x04 \x01(\v2\x14.banking.TransactionR\vtransaction\x12S\n" +
	"\x16client_request_message\x18\x05 \x01(\v2\x1d.banking.ClientRequestMessageR\x14clientRequestMessage\"\xb5\x01\n" +
	"\x15CommitMessageResponse\x127\n" +
	"\fmessage_type\x18\x01 \x01(\x0e2\x14.banking.MessageTypeR\vmessageType\x12:\n" +
	"\rballot_number\x18\x02 \x01(\v2\x15.banking.BallotNumberR\fballotNumber\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\x05R\x0esequenceNumber\"8\n" +
	"\rStatusRequest\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x05R\x0esequenceNumber\"\xbf\x01\n" +
	"\x0eStatusResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x05R\x0esequenceNumber\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12S\n" +
	"\x16client_request_message\x18\x04 \x01(\v2\x1d.banking.ClientRequestMessageR\x14clientRequestMessage\"\v\n" +
	"\tDBRequest\"\xa1\x01\n" +
	"\n" +
	"DBResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12=\n" +
	"\bbalances\x18\x02 \x03(\v2!.banking.DBResponse.BalancesEntryR\bbalances\x1a;\n" +
	"\rBalancesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\f\n" +
	"\n" +
	"LogRequest\"\xd4\x01\n" +
	"\x0fLogEntryMessage\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x05R\x0esequenceNumber\x12:\n" +
	"\rballot_number\x18\x02 \x01(\v2\x15.banking.BallotNumberR\fballotNumber\x12D\n" +
	"\x0eclient_request\x18\x03 \x01(\v2\x1d.banking.ClientRequestMessageR\rclientRequest\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"Z\n" +
	"\vLogResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x122\n" +
	"\aentries\x18\x02 \x03(\v2\x18.banking.LogEntryMessageR\aentries\"\xcf\x01\n" +
	"\x0eAcceptLogEntry\x12:\n" +
	"\rballot_number\x18\x01 \x01(\v2\x15.banking.BallotNumberR\fballotNumber\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x05R\x0esequenceNumber\x12@\n" +
	"\faccept_value\x18\x03 \x01(\v2\x1d.banking.ClientRequestMessageR\vacceptValue\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"L\n" +
	"\x0ePrepareMessage\x12:\n" +
	"\rballot_number\x18\x01 \x01(\v2\x15.banking.BallotNumberR\fballotNumber\"\xa6\x01\n" +
	"\x0ePromiseMessage\x12:\n" +
	"\rballot_number\x18\x01 \x01(\v2\x15.banking.BallotNumberR\fballotNumber\x126\n" +
	"\n" +
	"accept_log\x18\x02 \x03(\v2\x17.banking.AcceptLogEntryR\tacceptLog\x12 \n" +
	"\ffrom_node_id\x18\x03 \x01(\x05R\n" +
	"fromNodeId\"\x84\x01\n" +
	"\x0eNewViewRequest\x12:\n" +
	"\rballot_number\x18\x01 \x01(\v2\x15.banking.BallotNumberR\fballotNumber\x126\n" +
	"\n" +
	"accept_log\x18\x02 \x03(\v2\x17.banking.AcceptLogEntryR\tacceptLog\"i\n" +
	"\x0fNewViewResponse\x12V\n" +
	"\x17accept_message_response\x18\x01 \x03(\v2\x1e.banking.AcceptMessageResponseR\x15acceptMessageResponse\"k\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tleader_id\x18\x01 \x01(\x05R\bleaderId\x12:\n" +
	"\rballot_number\x18\x02 \x01(\v2\x15.banking.BallotNumberR\fballotNumber\"%\n" +
	"\x11HeartbeatResponse\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\bR\x03ack\"E\n" +
	"\fAliveRequest\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive\x12\x1f\n" +
	"\valive_nodes\x18\x02 \x03(\x05R\n" +
	"aliveNodes\")\n" +
	"\rAliveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x12\n" +
	"\x10PrintViewRequest\"V\n" +
	"\x11PrintViewResponse\x12A\n" +
	"\x10new_view_request\x18\x01 \x03(\v2\x17.banking.NewViewRequestR\x0enewViewRequest\"\x1a\n" +
	"\x18FailCurrentLeaderRequest\"\x1b\n" +
	"\x19FailCurrentLeaderResponse\"\x11\n" +
	"\x0fPrintLogRequest\"X\n" +
	"\x10PrintLogResponse\x12D\n" +
	"\x11log_entry_message\x18\x01 \x03(\v2\x18.banking.LogEntryMessageR\x0flogEntryMessage\"]\n" +
	"\x14ActiveCatchUpRequest\x12E\n" +
	"\x12accept_log_entries\x18\x01 \x03(\v2\x17.banking.AcceptLogEntryR\x10acceptLogEntries\"\x17\n" +
	"\x15ActiveCatchUpResponse*w\n" +
	"\vMessageType\x12\v\n" +
	"\aREQUEST\x10\x00\x12\f\n" +
	"\bRESPONSE\x10\x01\x12\n" +
	"\n" +
	"\x06ACCEPT\x10\x02\x12\f\n" +
	"\bACCEPTED\x10\x03\x12\n" +
	"\n" +
	"\x06COMMIT\x10\x04\x12\f\n" +
	"\bCOMMITED\x10\x05\x12\v\n" +
	"\aEXECUTE\x10\x06\x12\f\n" +
	"\bEXECUTED\x10\a2\xab\b\n" +
	"\x0fBankApplication\x12N\n" +
	"\rAcceptMessage\x12\x1d.banking.AcceptMessageRequest\x1a\x1e.banking.AcceptMessageResponse\x12N\n" +
	"\rCommitMessage\x12\x1d.banking.CommitMessageRequest\x1a\x1e.banking.CommitMessageResponse\x12:\n" +
	"\aPrepare\x12\x17.banking.PrepareMessage\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\aPromise\x12\x17.banking.PromiseMessage\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\aNewView\x12\x17.banking.NewViewRequest\x1a\x18.banking.NewViewResponse\x12B\n" +
	"\tHeartbeat\x12\x19.banking.HeartbeatRequest\x1a\x1a.banking.HeartbeatResponse\x12A\n" +
	"\x10UpdateNodeStatus\x12\x15.banking.AliveRequest\x1a\x16.banking.AliveResponse\x12Z\n" +
	"\x11FailCurrentLeader\x12!.banking.FailCurrentLeaderRequest\x1a\".banking.FailCurrentLeaderResponse\x12T\n" +
	"\x13HandleClientRequest\x12\x1d.banking.ClientRequestMessage\x1a\x1e.banking.ClientResponseMessage\x12<\n" +
	"\tGetStatus\x12\x16.banking.StatusRequest\x1a\x17.banking.StatusResponse\x120\n" +
	"\x05GetDB\x12\x12.banking.DBRequest\x1a\x13.banking.DBResponse\x123\n" +
	"\x06GetLog\x12\x13.banking.LogRequest\x1a\x14.banking.LogResponse\x12B\n" +
	"\tPrintView\x12\x19.banking.PrintViewRequest\x1a\x1a.banking.PrintViewResponse\x12?\n" +
	"\bPrintLog\x12\x18.banking.PrintLogRequest\x1a\x19.banking.PrintLogResponse\x12_\n" +
	"\x1ePerformActiveCatchUpAsFollower\x12\x1d.banking.ActiveCatchUpRequest\x1a\x1e.banking.ActiveCatchUpResponseB\x15Z\x13bank-application/pbb\x06proto3"

var (
	file_proto_paxos_proto_rawDescOnce sync.Once
	file_proto_paxos_proto_rawDescData []byte
)

func file_proto_paxos_proto_rawDescGZIP() []byte {
	file_proto_paxos_proto_rawDescOnce.Do(func() {
		file_proto_paxos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_paxos_proto_rawDesc), len(file_proto_paxos_proto_rawDesc)))
	})
	return file_proto_paxos_proto_rawDescData
}

var file_proto_paxos_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_paxos_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_proto_paxos_proto_goTypes = []any{
	(MessageType)(0),                  // 0: banking.MessageType
	(*Transaction)(nil),               // 1: banking.Transaction
	(*BallotNumber)(nil),              // 2: banking.BallotNumber
	(*ClientRequestMessage)(nil),      // 3: banking.ClientRequestMessage
	(*Result)(nil),                    // 4: banking.Result
	(*ClientResponseMessage)(nil),     // 5: banking.ClientResponseMessage
	(*AcceptMessageRequest)(nil),      // 6: banking.AcceptMessageRequest
	(*AcceptMessageResponse)(nil),     // 7: banking.AcceptMessageResponse
	(*CommitMessageRequest)(nil),      // 8: banking.CommitMessageRequest
	(*CommitMessageResponse)(nil),     // 9: banking.CommitMessageResponse
	(*StatusRequest)(nil),             // 10: banking.StatusRequest
	(*StatusResponse)(nil),            // 11: banking.StatusResponse
	(*DBRequest)(nil),                 // 12: banking.DBRequest
	(*DBResponse)(nil),                // 13: banking.DBResponse
	(*LogRequest)(nil),                // 14: banking.LogRequest
	(*LogEntryMessage)(nil),           // 15: banking.LogEntryMessage
	(*LogResponse)(nil),               // 16: banking.LogResponse
	(*AcceptLogEntry)(nil),            // 17: banking.AcceptLogEntry
	(*PrepareMessage)(nil),            // 18: banking.PrepareMessage
	(*PromiseMessage)(nil),            // 19: banking.PromiseMessage
	(*NewViewRequest)(nil),            // 20: banking.NewViewRequest
	(*NewViewResponse)(nil),           // 21: banking.NewViewResponse
	(*HeartbeatRequest)(nil),          // 22: banking.HeartbeatRequest
	(*HeartbeatResponse)(nil),         // 23: banking.HeartbeatResponse
	(*AliveRequest)(nil),              // 24: banking.AliveRequest
	(*AliveResponse)(nil),             // 25: banking.AliveResponse
	(*PrintViewRequest)(nil),          // 26: banking.PrintViewRequest
	(*PrintViewResponse)(nil),         // 27: banking.PrintViewResponse
	(*FailCurrentLeaderRequest)(nil),  // 28: banking.FailCurrentLeaderRequest
	(*FailCurrentLeaderResponse)(nil), // 29: banking.FailCurrentLeaderResponse
	(*PrintLogRequest)(nil),           // 30: banking.PrintLogRequest
	(*PrintLogResponse)(nil),          // 31: banking.PrintLogResponse
	(*ActiveCatchUpRequest)(nil),      // 32: banking.ActiveCatchUpRequest
	(*ActiveCatchUpResponse)(nil),     // 33: banking.ActiveCatchUpResponse
	nil,                               // 34: banking.DBResponse.BalancesEntry
	(*emptypb.Empty)(nil),             // 35: google.protobuf.Empty
}
var file_proto_paxos_proto_depIdxs = []int32{
	0,  // 0: banking.ClientRequestMessage.message_type:type_name -> banking.MessageType
	1,  // 1: banking.ClientRequestMessage.transaction:type_name -> banking.Transaction
	0,  // 2: banking.ClientResponseMessage.message_type:type_name -> banking.MessageType
	2,  // 3: banking.ClientResponseMessage.ballot_no:type_name -> banking.BallotNumber
	4,  // 4: banking.ClientResponseMessage.result_struct:type_name -> banking.Result
	0,  // 5: banking.AcceptMessageRequest.message_type:type_name -> banking.MessageType
	2,  // 6: banking.AcceptMessageRequest.ballot_number:type_name -> banking.BallotNumber
	1,  // 7: banking.AcceptMessageRequest.transaction:type_name -> banking.Transaction
	3,  // 8: banking.AcceptMessageRequest.client_request_message:type_name -> banking.ClientRequestMessage
	0,  // 9: banking.AcceptMessageResponse.message_type:type_name -> banking.MessageType
	2,  // 10: banking.AcceptMessageResponse.ballot_number:type_name -> banking.BallotNumber
	1,  // 11: banking.AcceptMessageResponse.transaction:type_name -> banking.Transaction
	0,  // 12: banking.CommitMessageRequest.message_type:type_name -> banking.MessageType
	2,  // 13: banking.CommitMessageRequest.ballot_number:type_name -> banking.BallotNumber
	1,  // 14: banking.CommitMessageRequest.transaction:type_name -> banking.Transaction
	3,  // 15: banking.CommitMessageRequest.client_request_message:type_name -> banking.ClientRequestMessage
	0,  // 16: banking.CommitMessageResponse.message_type:type_name -> banking.MessageType
	2,  // 17: banking.CommitMessageResponse.ballot_number:type_name -> banking.BallotNumber
	3,  // 18: banking.StatusResponse.client_request_message:type_name -> banking.ClientRequestMessage
	34, // 19: banking.DBResponse.balances:type_name -> banking.DBResponse.BalancesEntry
	2,  // 20: banking.LogEntryMessage.ballot_number:type_name -> banking.BallotNumber
	3,  // 21: banking.LogEntryMessage.client_request:type_name -> banking.ClientRequestMessage
	15, // 22: banking.LogResponse.entries:type_name -> banking.LogEntryMessage
	2,  // 23: banking.AcceptLogEntry.ballot_number:type_name -> banking.BallotNumber
	3,  // 24: banking.AcceptLogEntry.accept_value:type_name -> banking.ClientRequestMessage
	2,  // 25: banking.PrepareMessage.ballot_number:type_name -> banking.BallotNumber
	2,  // 26: banking.PromiseMessage.ballot_number:type_name -> banking.BallotNumber
	17, // 27: banking.PromiseMessage.accept_log:type_name -> banking.AcceptLogEntry
	2,  // 28: banking.NewViewRequest.ballot_number:type_name -> banking.BallotNumber
	17, // 29: banking.NewViewRequest.accept_log:type_name -> banking.AcceptLogEntry
	7,  // 30: banking.NewViewResponse.accept_message_response:type_name -> banking.AcceptMessageResponse
	2,  // 31: banking.HeartbeatRequest.ballot_number:type_name -> banking.BallotNumber
	20, // 32: banking.PrintViewResponse.new_view_request:type_name -> banking.NewViewRequest
	15, // 33: banking.PrintLogResponse.log_entry_message:type_name -> banking.LogEntryMessage
	17, // 34: banking.ActiveCatchUpRequest.accept_log_entries:type_name -> banking.AcceptLogEntry
	6,  // 35: banking.BankApplication.AcceptMessage:input_type -> banking.AcceptMessageRequest
	8,  // 36: banking.BankApplication.CommitMessage:input_type -> banking.CommitMessageRequest
	18, // 37: banking.BankApplication.Prepare:input_type -> banking.PrepareMessage
	19, // 38: banking.BankApplication.Promise:input_type -> banking.PromiseMessage
	20, // 39: banking.BankApplication.NewView:input_type -> banking.NewViewRequest
	22, // 40: banking.BankApplication.Heartbeat:input_type -> banking.HeartbeatRequest
	24, // 41: banking.BankApplication.UpdateNodeStatus:input_type -> banking.AliveRequest
	28, // 42: banking.BankApplication.FailCurrentLeader:input_type -> banking.FailCurrentLeaderRequest
	3,  // 43: banking.BankApplication.HandleClientRequest:input_type -> banking.ClientRequestMessage
	10, // 44: banking.BankApplication.GetStatus:input_type -> banking.StatusRequest
	12, // 45: banking.BankApplication.GetDB:input_type -> banking.DBRequest
	14, // 46: banking.BankApplication.GetLog:input_type -> banking.LogRequest
	26, // 47: banking.BankApplication.PrintView:input_type -> banking.PrintViewRequest
	30, // 48: banking.BankApplication.PrintLog:input_type -> banking.PrintLogRequest
	32, // 49: banking.BankApplication.PerformActiveCatchUpAsFollower:input_type -> banking.ActiveCatchUpRequest
	7,  // 50: banking.BankApplication.AcceptMessage:output_type -> banking.AcceptMessageResponse
	9,  // 51: banking.BankApplication.CommitMessage:output_type -> banking.CommitMessageResponse
	35, // 52: banking.BankApplication.Prepare:output_type -> google.protobuf.Empty
	35, // 53: banking.BankApplication.Promise:output_type -> google.protobuf.Empty
	21, // 54: banking.BankApplication.NewView:output_type -> banking.NewViewResponse
	23, // 55: banking.BankApplication.Heartbeat:output_type -> banking.HeartbeatResponse
	25, // 56: banking.BankApplication.UpdateNodeStatus:output_type -> banking.AliveResponse
	29, // 57: banking.BankApplication.FailCurrentLeader:output_type -> banking.FailCurrentLeaderResponse
	5,  // 58: banking.BankApplication.HandleClientRequest:output_type -> banking.ClientResponseMessage
	11, // 59: banking.BankApplication.GetStatus:output_type -> banking.StatusResponse
	13, // 60: banking.BankApplication.GetDB:output_type -> banking.DBResponse
	16, // 61: banking.BankApplication.GetLog:output_type -> banking.LogResponse
	27, // 62: banking.BankApplication.PrintView:output_type -> banking.PrintViewResponse
	31, // 63: banking.BankApplication.PrintLog:output_type -> banking.PrintLogResponse
	33, // 64: banking.BankApplication.PerformActiveCatchUpAsFollower:output_type -> banking.ActiveCatchUpResponse
	50, // [50:65] is the sub-list for method output_type
	35, // [35:50] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_proto_paxos_proto_init() }
func file_proto_paxos_proto_init() {
	if File_proto_paxos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_paxos_proto_rawDesc), len(file_proto_paxos_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_paxos_proto_goTypes,
		DependencyIndexes: file_proto_paxos_proto_depIdxs,
		EnumInfos:         file_proto_paxos_proto_enumTypes,
		MessageInfos:      file_proto_paxos_proto_msgTypes,
	}.Build()
	File_proto_paxos_proto = out.File
	file_proto_paxos_proto_goTypes = nil
	file_proto_paxos_proto_depIdxs = nil
}
