// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.3
// source: proto/client_control.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReshardMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       int32                  `protobuf:"varint,1,opt,name=account,proto3" json:"account,omitempty"`
	FromCluster   int32                  `protobuf:"varint,2,opt,name=from_cluster,json=fromCluster,proto3" json:"from_cluster,omitempty"`
	ToCluster     int32                  `protobuf:"varint,3,opt,name=to_cluster,json=toCluster,proto3" json:"to_cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReshardMove) Reset() {
	*x = ReshardMove{}
	mi := &file_proto_client_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReshardMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReshardMove) ProtoMessage() {}

func (x *ReshardMove) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReshardMove.ProtoReflect.Descriptor instead.
func (*ReshardMove) Descriptor() ([]byte, []int) {
	return file_proto_client_control_proto_rawDescGZIP(), []int{0}
}

func (x *ReshardMove) GetAccount() int32 {
	if x != nil {
		return x.Account
	}
	return 0
}

func (x *ReshardMove) GetFromCluster() int32 {
	if x != nil {
		return x.FromCluster
	}
	return 0
}

func (x *ReshardMove) GetToCluster() int32 {
	if x != nil {
		return x.ToCluster
	}
	return 0
}

type GetReshardPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReshardPlanRequest) Reset() {
	*x = GetReshardPlanRequest{}
	mi := &file_proto_client_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReshardPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReshardPlanRequest) ProtoMessage() {}

func (x *GetReshardPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReshardPlanRequest.ProtoReflect.Descriptor instead.
func (*GetReshardPlanRequest) Descriptor() ([]byte, []int) {
	return file_proto_client_control_proto_rawDescGZIP(), []int{1}
}

type GetReshardPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moves         []*ReshardMove         `protobuf:"bytes,1,rep,name=moves,proto3" json:"moves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReshardPlanResponse) Reset() {
	*x = GetReshardPlanResponse{}
	mi := &file_proto_client_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReshardPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReshardPlanResponse) ProtoMessage() {}

func (x *GetReshardPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReshardPlanResponse.ProtoReflect.Descriptor instead.
func (*GetReshardPlanResponse) Descriptor() ([]byte, []int) {
	return file_proto_client_control_proto_rawDescGZIP(), []int{2}
}

func (x *GetReshardPlanResponse) GetMoves() []*ReshardMove {
	if x != nil {
		return x.Moves
	}
	return nil
}

type PerformanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Set           int32                  `protobuf:"varint,1,opt,name=set,proto3" json:"set,omitempty"` // 0 = most recent completed set
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerformanceRequest) Reset() {
	*x = PerformanceRequest{}
	mi := &file_proto_client_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformanceRequest) ProtoMessage() {}

func (x *PerformanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformanceRequest.ProtoReflect.Descriptor instead.
func (*PerformanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_client_control_proto_rawDescGZIP(), []int{3}
}

func (x *PerformanceRequest) GetSet() int32 {
	if x != nil {
		return x.Set
	}
	return 0
}

type PerformanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Throughput    float64                `protobuf:"fixed64,1,opt,name=throughput,proto3" json:"throughput,omitempty"`
	AvgLatencyMs  float64                `protobuf:"fixed64,2,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	Ops           int32                  `protobuf:"varint,3,opt,name=ops,proto3" json:"ops,omitempty"`
	P50LatencyMs  float64                `protobuf:"fixed64,4,opt,name=p50_latency_ms,json=p50LatencyMs,proto3" json:"p50_latency_ms,omitempty"`
	P95LatencyMs  float64                `protobuf:"fixed64,5,opt,name=p95_latency_ms,json=p95LatencyMs,proto3" json:"p95_latency_ms,omitempty"`
	P99LatencyMs  float64                `protobuf:"fixed64,6,opt,name=p99_latency_ms,json=p99LatencyMs,proto3" json:"p99_latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerformanceResponse) Reset() {
	*x = PerformanceResponse{}
	mi := &file_proto_client_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformanceResponse) ProtoMessage() {}

func (x *PerformanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_client_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformanceResponse.ProtoReflect.Descriptor instead.
func (*PerformanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_client_control_proto_rawDescGZIP(), []int{4}
}

func (x *PerformanceResponse) GetThroughput() float64 {
	if x != nil {
		return x.Throughput
	}
	return 0
}

func (x *PerformanceResponse) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *PerformanceResponse) GetOps() int32 {
	if x != nil {
		return x.Ops
	}
	return 0
}

func (x *PerformanceResponse) GetP50LatencyMs() float64 {
	if x != nil {
		return x.P50LatencyMs
	}
	return 0
}

func (x *PerformanceResponse) GetP95LatencyMs() float64 {
	if x != nil {
		return x.P95LatencyMs
	}
	return 0
}

func (x *PerformanceResponse) GetP99LatencyMs() float64 {
	if x != nil {
		return x.P99LatencyMs
	}
	return 0
}

var File_proto_client_control_proto protoreflect.FileDescriptor

const file_proto_client_control_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/client_control.proto\x12\abanking\"i\n" +
	"\vReshardMove\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\x05R\aaccount\x12!\n" +
	"\ffrom_cluster\x18\x02 \x01(\x05R\vfromCluster\x12\x1d\n" +
	"\n" +
	"to_cluster\x18\x03 \x01(\x05R\ttoCluster\"\x17\n" +
	"\x15GetReshardPlanRequest\"D\n" +
	"\x16GetReshardPlanResponse\x12*\n" +
	"\x05moves\x18\x01 \x03(\v2\x14.banking.ReshardMoveR\x05moves\"&\n" +
	"\x12PerformanceRequest\x12\x10\n" +
	"\x03set\x18\x01 \x01(\x05R\x03set\"\xdf\x01\n" +
	"\x13PerformanceResponse\x12\x1e\n" +
	"\n" +
	"throughput\x18\x01 \x01(\x01R\n" +
	"throughput\x12$\n" +
	"\x0eavg_latency_ms\x18\x02 \x01(\x01R\favgLatencyMs\x12\x10\n" +
	"\x03ops\x18\x03 \x01(\x05R\x03ops\x12$\n" +
	"\x0ep50_latency_ms\x18\x04 \x01(\x01R\fp50LatencyMs\x12$\n" +
	"\x0ep95_latency_ms\x18\x05 \x01(\x01R\fp95LatencyMs\x12$\n" +
	"\x0ep99_latency_ms\x18\x06 \x01(\x01R\fp99LatencyMs2\xac\x01\n" +
	"\rClientControl\x12Q\n" +
	"\x0eGetReshardPlan\x12\x1e.banking.GetReshardPlanRequest\x1a\x1f.banking.GetReshardPlanResponse\x12H\n" +
	"\vPerformance\x12\x1b.banking.PerformanceRequest\x1a\x1c.banking.PerformanceResponseB\x18Z\x16pb/bank-application/pbb\x06proto3"

var (
	file_proto_client_control_proto_rawDescOnce sync.Once
	file_proto_client_control_proto_rawDescData []byte
)

func file_proto_client_control_proto_rawDescGZIP() []byte {
	file_proto_client_control_proto_rawDescOnce.Do(func() {
		file_proto_client_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_client_control_proto_rawDesc), len(file_proto_client_control_proto_rawDesc)))
	})
	return file_proto_client_control_proto_rawDescData
}

var file_proto_client_control_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_client_control_proto_goTypes = []any{
	(*ReshardMove)(nil),            // 0: banking.ReshardMove
	(*GetReshardPlanRequest)(nil),  // 1: banking.GetReshardPlanRequest
	(*GetReshardPlanResponse)(nil), // 2: banking.GetReshardPlanResponse
	(*PerformanceRequest)(nil),     // 3: banking.PerformanceRequest
	(*PerformanceResponse)(nil),    // 4: banking.PerformanceResponse
}
var file_proto_client_control_proto_depIdxs = []int32{
	0, // 0: banking.GetReshardPlanResponse.moves:type_name -> banking.ReshardMove
	1, // 1: banking.ClientControl.GetReshardPlan:input_type -> banking.GetReshardPlanRequest
	3, // 2: banking.ClientControl.Performance:input_type -> banking.PerformanceRequest
	2, // 3: banking.ClientControl.GetReshardPlan:output_type -> banking.GetReshardPlanResponse
	4, // 4: banking.ClientControl.Performance:output_type -> banking.PerformanceResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_client_control_proto_init() }
func file_proto_client_control_proto_init() {
	if File_proto_client_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_client_control_proto_rawDesc), len(file_proto_client_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_client_control_proto_goTypes,
		DependencyIndexes: file_proto_client_control_proto_depIdxs,
		MessageInfos:      file_proto_client_control_proto_msgTypes,
	}.Build()
	File_proto_client_control_proto = out.File
	file_proto_client_control_proto_goTypes = nil
	file_proto_client_control_proto_depIdxs = nil
}
