// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: proto/client_control.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientControl_GetReshardPlan_FullMethodName = "/banking.ClientControl/GetReshardPlan"
)

// ClientControlClient is the client API for ClientControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientControlClient interface {
	GetReshardPlan(ctx context.Context, in *GetReshardPlanRequest, opts ...grpc.CallOption) (*GetReshardPlanResponse, error)
}

type clientControlClient struct {
	cc grpc.ClientConnInterface
}

func NewClientControlClient(cc grpc.ClientConnInterface) ClientControlClient {
	return &clientControlClient{cc}
}

func (c *clientControlClient) GetReshardPlan(ctx context.Context, in *GetReshardPlanRequest, opts ...grpc.CallOption) (*GetReshardPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReshardPlanResponse)
	err := c.cc.Invoke(ctx, ClientControl_GetReshardPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientControlServer is the server API for ClientControl service.
// All implementations must embed UnimplementedClientControlServer
// for forward compatibility.
type ClientControlServer interface {
	GetReshardPlan(context.Context, *GetReshardPlanRequest) (*GetReshardPlanResponse, error)
	mustEmbedUnimplementedClientControlServer()
}

// UnimplementedClientControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientControlServer struct{}

func (UnimplementedClientControlServer) GetReshardPlan(context.Context, *GetReshardPlanRequest) (*GetReshardPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReshardPlan not implemented")
}
func (UnimplementedClientControlServer) mustEmbedUnimplementedClientControlServer() {}
func (UnimplementedClientControlServer) testEmbeddedByValue()                       {}

// UnsafeClientControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientControlServer will
// result in compilation errors.
type UnsafeClientControlServer interface {
	mustEmbedUnimplementedClientControlServer()
}

func RegisterClientControlServer(s grpc.ServiceRegistrar, srv ClientControlServer) {
	// If the following call pancis, it indicates UnimplementedClientControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientControl_ServiceDesc, srv)
}

func _ClientControl_GetReshardPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReshardPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientControlServer).GetReshardPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientControl_GetReshardPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientControlServer).GetReshardPlan(ctx, req.(*GetReshardPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientControl_ServiceDesc is the grpc.ServiceDesc for ClientControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "banking.ClientControl",
	HandlerType: (*ClientControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetReshardPlan",
			Handler:    _ClientControl_GetReshardPlan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/client_control.proto",
}
