// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: proto/paxos.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BankApplication_AcceptMessage_FullMethodName                         = "/banking.BankApplication/AcceptMessage"
	BankApplication_CommitMessage_FullMethodName                         = "/banking.BankApplication/CommitMessage"
	BankApplication_Prepare_FullMethodName                               = "/banking.BankApplication/Prepare"
	BankApplication_Promise_FullMethodName                               = "/banking.BankApplication/Promise"
	BankApplication_NewView_FullMethodName                               = "/banking.BankApplication/NewView"
	BankApplication_Heartbeat_FullMethodName                             = "/banking.BankApplication/Heartbeat"
	BankApplication_UpdateNodeStatus_FullMethodName                      = "/banking.BankApplication/UpdateNodeStatus"
	BankApplication_FailCurrentLeader_FullMethodName                     = "/banking.BankApplication/FailCurrentLeader"
	BankApplication_HandleClientRequest_FullMethodName                   = "/banking.BankApplication/HandleClientRequest"
	BankApplication_GetStatus_FullMethodName                             = "/banking.BankApplication/GetStatus"
	BankApplication_GetDB_FullMethodName                                 = "/banking.BankApplication/GetDB"
	BankApplication_GetLog_FullMethodName                                = "/banking.BankApplication/GetLog"
	BankApplication_PrintView_FullMethodName                             = "/banking.BankApplication/PrintView"
	BankApplication_PrintLog_FullMethodName                              = "/banking.BankApplication/PrintLog"
	BankApplication_PrintBalance_FullMethodName                          = "/banking.BankApplication/PrintBalance"
	BankApplication_PerformActiveCatchUpAsFollower_FullMethodName        = "/banking.BankApplication/PerformActiveCatchUpAsFollower"
	BankApplication_GetLeaderLogForActiveCatching_FullMethodName         = "/banking.BankApplication/GetLeaderLogForActiveCatching"
	BankApplication_FlushPreviousDataAndUpdatePeersStatus_FullMethodName = "/banking.BankApplication/FlushPreviousDataAndUpdatePeersStatus"
	BankApplication_ReadClientBalance_FullMethodName                     = "/banking.BankApplication/ReadClientBalance"
	BankApplication_GetClusterLeader_FullMethodName                      = "/banking.BankApplication/GetClusterLeader"
	BankApplication_Prepare2PC_FullMethodName                            = "/banking.BankApplication/Prepare2PC"
	BankApplication_CommitOrAbort2PC_FullMethodName                      = "/banking.BankApplication/CommitOrAbort2PC"
	BankApplication_AcceptMessageFor2PCCommit_FullMethodName             = "/banking.BankApplication/AcceptMessageFor2PCCommit"
	BankApplication_CommitMessageFor2PCCommit_FullMethodName             = "/banking.BankApplication/CommitMessageFor2PCCommit"
)

// BankApplicationClient is the client API for BankApplication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BankApplicationClient interface {
	AcceptMessage(ctx context.Context, in *AcceptMessageRequest, opts ...grpc.CallOption) (*AcceptMessageResponse, error)
	CommitMessage(ctx context.Context, in *CommitMessageRequest, opts ...grpc.CallOption) (*CommitMessageResponse, error)
	// For leader election
	Prepare(ctx context.Context, in *PrepareMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Promise(ctx context.Context, in *PromiseMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	NewView(ctx context.Context, in *NewViewRequest, opts ...grpc.CallOption) (*NewViewResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	UpdateNodeStatus(ctx context.Context, in *AliveRequest, opts ...grpc.CallOption) (*AliveResponse, error)
	FailCurrentLeader(ctx context.Context, in *FailCurrentLeaderRequest, opts ...grpc.CallOption) (*FailCurrentLeaderResponse, error)
	// CLIENT RPC's
	HandleClientRequest(ctx context.Context, in *ClientRequestMessage, opts ...grpc.CallOption) (*ClientResponseMessage, error)
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	GetDB(ctx context.Context, in *DBRequest, opts ...grpc.CallOption) (*DBResponse, error)
	// not using now, replaced by PrintLog
	GetLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
	PrintView(ctx context.Context, in *PrintViewRequest, opts ...grpc.CallOption) (*PrintViewResponse, error)
	PrintLog(ctx context.Context, in *PrintLogRequest, opts ...grpc.CallOption) (*PrintLogResponse, error)
	PrintBalance(ctx context.Context, in *PrintBalanceRequest, opts ...grpc.CallOption) (*PrintBalanceResponse, error)
	PerformActiveCatchUpAsFollower(ctx context.Context, in *ActiveCatchUpRequest, opts ...grpc.CallOption) (*ActiveCatchUpResponse, error)
	GetLeaderLogForActiveCatching(ctx context.Context, in *GetLeaderLogRequest, opts ...grpc.CallOption) (*GetLeaderLogResponse, error)
	FlushPreviousDataAndUpdatePeersStatus(ctx context.Context, in *FlushAndUpdateStatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReadClientBalance(ctx context.Context, in *ReadClientBalanceRequest, opts ...grpc.CallOption) (*ReadClientBalanceResponse, error)
	// 2PC
	GetClusterLeader(ctx context.Context, in *GetClusterLeaderRequest, opts ...grpc.CallOption) (*GetClusterLeaderResponse, error)
	Prepare2PC(ctx context.Context, in *Prepare2PCRequest, opts ...grpc.CallOption) (*Prepare2PCResponse, error)
	CommitOrAbort2PC(ctx context.Context, in *CommitOrAbort2PCRequest, opts ...grpc.CallOption) (*CommitOrAbort2PCResponse, error)
	AcceptMessageFor2PCCommit(ctx context.Context, in *AcceptMessageFor2PCCommitRequest, opts ...grpc.CallOption) (*AcceptMessageFor2PCCommitResponse, error)
	CommitMessageFor2PCCommit(ctx context.Context, in *CommitMessageFor2PCCommitRequest, opts ...grpc.CallOption) (*CommitMessageFor2PCCommitResponse, error)
}

type bankApplicationClient struct {
	cc grpc.ClientConnInterface
}

func NewBankApplicationClient(cc grpc.ClientConnInterface) BankApplicationClient {
	return &bankApplicationClient{cc}
}

func (c *bankApplicationClient) AcceptMessage(ctx context.Context, in *AcceptMessageRequest, opts ...grpc.CallOption) (*AcceptMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptMessageResponse)
	err := c.cc.Invoke(ctx, BankApplication_AcceptMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankApplicationClient) CommitMessage(ctx context.Context, in *CommitMessageRequest, opts ...grpc.CallOption) (*CommitMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitMessageResponse)
	err := c.cc.Invoke(ctx, BankApplication_CommitMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankApplicationClient) Prepare(ctx context.Context, in *PrepareMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BankApplication_Prepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankApplicationClient) Promise(ctx context.Context, in *PromiseMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BankApplication_Promise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankApplicationClient) NewView(ctx context.Context, in *NewViewRequest, opts ...grpc.CallOption) (*NewViewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewViewResponse)
	err := c.cc.Invoke(ctx, BankApplication_NewView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankApplicationClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, BankApplication_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankApplicationClient) UpdateNodeStatus(ctx context.Context, in *AliveRequest, opts ...grpc.CallOption) (*AliveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AliveResponse)
	err := c.cc.Invoke(ctx, BankApplication_UpdateNodeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankApplicationClient) FailCurrentLeader(ctx context.Context, in *FailCurrentLeaderRequest, opts ...grpc.CallOption) (*FailCurrentLeaderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FailCurrentLeaderResponse)
	err := c.cc.Invoke(ctx, BankApplication_FailCurrentLeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankApplicationClient) HandleClientRequest(ctx context.Context, in *ClientRequestMessage, opts ...grpc.CallOption) (*ClientResponseMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientResponseMessage)
	err := c.cc.Invoke(ctx, BankApplication_HandleClientRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankApplicationClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, BankApplication_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankApplicationClient) GetDB(ctx context.Context, in *DBRequest, opts ...grpc.CallOption) (*DBResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DBResponse)
	err := c.cc.Invoke(ctx, BankApplication_GetDB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankApplicationClient) GetLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, BankApplication_GetLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankApplicationClient) PrintView(ctx context.Context, in *PrintViewRequest, opts ...grpc.CallOption) (*PrintViewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintViewResponse)
	err := c.cc.Invoke(ctx, BankApplication_PrintView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankApplicationClient) PrintLog(ctx context.Context, in *PrintLogRequest, opts ...grpc.CallOption) (*PrintLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintLogResponse)
	err := c.cc.Invoke(ctx, BankApplication_PrintLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankApplicationClient) PrintBalance(ctx context.Context, in *PrintBalanceRequest, opts ...grpc.CallOption) (*PrintBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintBalanceResponse)
	err := c.cc.Invoke(ctx, BankApplication_PrintBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankApplicationClient) PerformActiveCatchUpAsFollower(ctx context.Context, in *ActiveCatchUpRequest, opts ...grpc.CallOption) (*ActiveCatchUpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActiveCatchUpResponse)
	err := c.cc.Invoke(ctx, BankApplication_PerformActiveCatchUpAsFollower_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankApplicationClient) GetLeaderLogForActiveCatching(ctx context.Context, in *GetLeaderLogRequest, opts ...grpc.CallOption) (*GetLeaderLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLeaderLogResponse)
	err := c.cc.Invoke(ctx, BankApplication_GetLeaderLogForActiveCatching_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankApplicationClient) FlushPreviousDataAndUpdatePeersStatus(ctx context.Context, in *FlushAndUpdateStatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BankApplication_FlushPreviousDataAndUpdatePeersStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankApplicationClient) ReadClientBalance(ctx context.Context, in *ReadClientBalanceRequest, opts ...grpc.CallOption) (*ReadClientBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadClientBalanceResponse)
	err := c.cc.Invoke(ctx, BankApplication_ReadClientBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankApplicationClient) GetClusterLeader(ctx context.Context, in *GetClusterLeaderRequest, opts ...grpc.CallOption) (*GetClusterLeaderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClusterLeaderResponse)
	err := c.cc.Invoke(ctx, BankApplication_GetClusterLeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankApplicationClient) Prepare2PC(ctx context.Context, in *Prepare2PCRequest, opts ...grpc.CallOption) (*Prepare2PCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Prepare2PCResponse)
	err := c.cc.Invoke(ctx, BankApplication_Prepare2PC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankApplicationClient) CommitOrAbort2PC(ctx context.Context, in *CommitOrAbort2PCRequest, opts ...grpc.CallOption) (*CommitOrAbort2PCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitOrAbort2PCResponse)
	err := c.cc.Invoke(ctx, BankApplication_CommitOrAbort2PC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankApplicationClient) AcceptMessageFor2PCCommit(ctx context.Context, in *AcceptMessageFor2PCCommitRequest, opts ...grpc.CallOption) (*AcceptMessageFor2PCCommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptMessageFor2PCCommitResponse)
	err := c.cc.Invoke(ctx, BankApplication_AcceptMessageFor2PCCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankApplicationClient) CommitMessageFor2PCCommit(ctx context.Context, in *CommitMessageFor2PCCommitRequest, opts ...grpc.CallOption) (*CommitMessageFor2PCCommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitMessageFor2PCCommitResponse)
	err := c.cc.Invoke(ctx, BankApplication_CommitMessageFor2PCCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BankApplicationServer is the server API for BankApplication service.
// All implementations must embed UnimplementedBankApplicationServer
// for forward compatibility.
type BankApplicationServer interface {
	AcceptMessage(context.Context, *AcceptMessageRequest) (*AcceptMessageResponse, error)
	CommitMessage(context.Context, *CommitMessageRequest) (*CommitMessageResponse, error)
	// For leader election
	Prepare(context.Context, *PrepareMessage) (*emptypb.Empty, error)
	Promise(context.Context, *PromiseMessage) (*emptypb.Empty, error)
	NewView(context.Context, *NewViewRequest) (*NewViewResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	UpdateNodeStatus(context.Context, *AliveRequest) (*AliveResponse, error)
	FailCurrentLeader(context.Context, *FailCurrentLeaderRequest) (*FailCurrentLeaderResponse, error)
	// CLIENT RPC's
	HandleClientRequest(context.Context, *ClientRequestMessage) (*ClientResponseMessage, error)
	GetStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	GetDB(context.Context, *DBRequest) (*DBResponse, error)
	// not using now, replaced by PrintLog
	GetLog(context.Context, *LogRequest) (*LogResponse, error)
	PrintView(context.Context, *PrintViewRequest) (*PrintViewResponse, error)
	PrintLog(context.Context, *PrintLogRequest) (*PrintLogResponse, error)
	PrintBalance(context.Context, *PrintBalanceRequest) (*PrintBalanceResponse, error)
	PerformActiveCatchUpAsFollower(context.Context, *ActiveCatchUpRequest) (*ActiveCatchUpResponse, error)
	GetLeaderLogForActiveCatching(context.Context, *GetLeaderLogRequest) (*GetLeaderLogResponse, error)
	FlushPreviousDataAndUpdatePeersStatus(context.Context, *FlushAndUpdateStatusRequest) (*emptypb.Empty, error)
	ReadClientBalance(context.Context, *ReadClientBalanceRequest) (*ReadClientBalanceResponse, error)
	// 2PC
	GetClusterLeader(context.Context, *GetClusterLeaderRequest) (*GetClusterLeaderResponse, error)
	Prepare2PC(context.Context, *Prepare2PCRequest) (*Prepare2PCResponse, error)
	CommitOrAbort2PC(context.Context, *CommitOrAbort2PCRequest) (*CommitOrAbort2PCResponse, error)
	AcceptMessageFor2PCCommit(context.Context, *AcceptMessageFor2PCCommitRequest) (*AcceptMessageFor2PCCommitResponse, error)
	CommitMessageFor2PCCommit(context.Context, *CommitMessageFor2PCCommitRequest) (*CommitMessageFor2PCCommitResponse, error)
	mustEmbedUnimplementedBankApplicationServer()
}

// UnimplementedBankApplicationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBankApplicationServer struct{}

func (UnimplementedBankApplicationServer) AcceptMessage(context.Context, *AcceptMessageRequest) (*AcceptMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptMessage not implemented")
}
func (UnimplementedBankApplicationServer) CommitMessage(context.Context, *CommitMessageRequest) (*CommitMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitMessage not implemented")
}
func (UnimplementedBankApplicationServer) Prepare(context.Context, *PrepareMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}
func (UnimplementedBankApplicationServer) Promise(context.Context, *PromiseMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Promise not implemented")
}
func (UnimplementedBankApplicationServer) NewView(context.Context, *NewViewRequest) (*NewViewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewView not implemented")
}
func (UnimplementedBankApplicationServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedBankApplicationServer) UpdateNodeStatus(context.Context, *AliveRequest) (*AliveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNodeStatus not implemented")
}
func (UnimplementedBankApplicationServer) FailCurrentLeader(context.Context, *FailCurrentLeaderRequest) (*FailCurrentLeaderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FailCurrentLeader not implemented")
}
func (UnimplementedBankApplicationServer) HandleClientRequest(context.Context, *ClientRequestMessage) (*ClientResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleClientRequest not implemented")
}
func (UnimplementedBankApplicationServer) GetStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedBankApplicationServer) GetDB(context.Context, *DBRequest) (*DBResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDB not implemented")
}
func (UnimplementedBankApplicationServer) GetLog(context.Context, *LogRequest) (*LogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLog not implemented")
}
func (UnimplementedBankApplicationServer) PrintView(context.Context, *PrintViewRequest) (*PrintViewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintView not implemented")
}
func (UnimplementedBankApplicationServer) PrintLog(context.Context, *PrintLogRequest) (*PrintLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintLog not implemented")
}
func (UnimplementedBankApplicationServer) PrintBalance(context.Context, *PrintBalanceRequest) (*PrintBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintBalance not implemented")
}
func (UnimplementedBankApplicationServer) PerformActiveCatchUpAsFollower(context.Context, *ActiveCatchUpRequest) (*ActiveCatchUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PerformActiveCatchUpAsFollower not implemented")
}
func (UnimplementedBankApplicationServer) GetLeaderLogForActiveCatching(context.Context, *GetLeaderLogRequest) (*GetLeaderLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeaderLogForActiveCatching not implemented")
}
func (UnimplementedBankApplicationServer) FlushPreviousDataAndUpdatePeersStatus(context.Context, *FlushAndUpdateStatusRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlushPreviousDataAndUpdatePeersStatus not implemented")
}
func (UnimplementedBankApplicationServer) ReadClientBalance(context.Context, *ReadClientBalanceRequest) (*ReadClientBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadClientBalance not implemented")
}
func (UnimplementedBankApplicationServer) GetClusterLeader(context.Context, *GetClusterLeaderRequest) (*GetClusterLeaderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterLeader not implemented")
}
func (UnimplementedBankApplicationServer) Prepare2PC(context.Context, *Prepare2PCRequest) (*Prepare2PCResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare2PC not implemented")
}
func (UnimplementedBankApplicationServer) CommitOrAbort2PC(context.Context, *CommitOrAbort2PCRequest) (*CommitOrAbort2PCResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitOrAbort2PC not implemented")
}
func (UnimplementedBankApplicationServer) AcceptMessageFor2PCCommit(context.Context, *AcceptMessageFor2PCCommitRequest) (*AcceptMessageFor2PCCommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptMessageFor2PCCommit not implemented")
}
func (UnimplementedBankApplicationServer) CommitMessageFor2PCCommit(context.Context, *CommitMessageFor2PCCommitRequest) (*CommitMessageFor2PCCommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitMessageFor2PCCommit not implemented")
}
func (UnimplementedBankApplicationServer) mustEmbedUnimplementedBankApplicationServer() {}
func (UnimplementedBankApplicationServer) testEmbeddedByValue()                         {}

// UnsafeBankApplicationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BankApplicationServer will
// result in compilation errors.
type UnsafeBankApplicationServer interface {
	mustEmbedUnimplementedBankApplicationServer()
}

func RegisterBankApplicationServer(s grpc.ServiceRegistrar, srv BankApplicationServer) {
	// If the following call pancis, it indicates UnimplementedBankApplicationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BankApplication_ServiceDesc, srv)
}

func _BankApplication_AcceptMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankApplicationServer).AcceptMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankApplication_AcceptMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankApplicationServer).AcceptMessage(ctx, req.(*AcceptMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankApplication_CommitMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankApplicationServer).CommitMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankApplication_CommitMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankApplicationServer).CommitMessage(ctx, req.(*CommitMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankApplication_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankApplicationServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankApplication_Prepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankApplicationServer).Prepare(ctx, req.(*PrepareMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankApplication_Promise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromiseMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankApplicationServer).Promise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankApplication_Promise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankApplicationServer).Promise(ctx, req.(*PromiseMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankApplication_NewView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankApplicationServer).NewView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankApplication_NewView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankApplicationServer).NewView(ctx, req.(*NewViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankApplication_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankApplicationServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankApplication_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankApplicationServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankApplication_UpdateNodeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AliveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankApplicationServer).UpdateNodeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankApplication_UpdateNodeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankApplicationServer).UpdateNodeStatus(ctx, req.(*AliveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankApplication_FailCurrentLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailCurrentLeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankApplicationServer).FailCurrentLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankApplication_FailCurrentLeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankApplicationServer).FailCurrentLeader(ctx, req.(*FailCurrentLeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankApplication_HandleClientRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankApplicationServer).HandleClientRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankApplication_HandleClientRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankApplicationServer).HandleClientRequest(ctx, req.(*ClientRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankApplication_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankApplicationServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankApplication_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankApplicationServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankApplication_GetDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankApplicationServer).GetDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankApplication_GetDB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankApplicationServer).GetDB(ctx, req.(*DBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankApplication_GetLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankApplicationServer).GetLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankApplication_GetLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankApplicationServer).GetLog(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankApplication_PrintView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankApplicationServer).PrintView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankApplication_PrintView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankApplicationServer).PrintView(ctx, req.(*PrintViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankApplication_PrintLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankApplicationServer).PrintLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankApplication_PrintLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankApplicationServer).PrintLog(ctx, req.(*PrintLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankApplication_PrintBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankApplicationServer).PrintBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankApplication_PrintBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankApplicationServer).PrintBalance(ctx, req.(*PrintBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankApplication_PerformActiveCatchUpAsFollower_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActiveCatchUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankApplicationServer).PerformActiveCatchUpAsFollower(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankApplication_PerformActiveCatchUpAsFollower_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankApplicationServer).PerformActiveCatchUpAsFollower(ctx, req.(*ActiveCatchUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankApplication_GetLeaderLogForActiveCatching_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaderLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankApplicationServer).GetLeaderLogForActiveCatching(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankApplication_GetLeaderLogForActiveCatching_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankApplicationServer).GetLeaderLogForActiveCatching(ctx, req.(*GetLeaderLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankApplication_FlushPreviousDataAndUpdatePeersStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushAndUpdateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankApplicationServer).FlushPreviousDataAndUpdatePeersStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankApplication_FlushPreviousDataAndUpdatePeersStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankApplicationServer).FlushPreviousDataAndUpdatePeersStatus(ctx, req.(*FlushAndUpdateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankApplication_ReadClientBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadClientBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankApplicationServer).ReadClientBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankApplication_ReadClientBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankApplicationServer).ReadClientBalance(ctx, req.(*ReadClientBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankApplication_GetClusterLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterLeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankApplicationServer).GetClusterLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankApplication_GetClusterLeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankApplicationServer).GetClusterLeader(ctx, req.(*GetClusterLeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankApplication_Prepare2PC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Prepare2PCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankApplicationServer).Prepare2PC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankApplication_Prepare2PC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankApplicationServer).Prepare2PC(ctx, req.(*Prepare2PCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankApplication_CommitOrAbort2PC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitOrAbort2PCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankApplicationServer).CommitOrAbort2PC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankApplication_CommitOrAbort2PC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankApplicationServer).CommitOrAbort2PC(ctx, req.(*CommitOrAbort2PCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankApplication_AcceptMessageFor2PCCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptMessageFor2PCCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankApplicationServer).AcceptMessageFor2PCCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankApplication_AcceptMessageFor2PCCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankApplicationServer).AcceptMessageFor2PCCommit(ctx, req.(*AcceptMessageFor2PCCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankApplication_CommitMessageFor2PCCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitMessageFor2PCCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankApplicationServer).CommitMessageFor2PCCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankApplication_CommitMessageFor2PCCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankApplicationServer).CommitMessageFor2PCCommit(ctx, req.(*CommitMessageFor2PCCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BankApplication_ServiceDesc is the grpc.ServiceDesc for BankApplication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BankApplication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "banking.BankApplication",
	HandlerType: (*BankApplicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AcceptMessage",
			Handler:    _BankApplication_AcceptMessage_Handler,
		},
		{
			MethodName: "CommitMessage",
			Handler:    _BankApplication_CommitMessage_Handler,
		},
		{
			MethodName: "Prepare",
			Handler:    _BankApplication_Prepare_Handler,
		},
		{
			MethodName: "Promise",
			Handler:    _BankApplication_Promise_Handler,
		},
		{
			MethodName: "NewView",
			Handler:    _BankApplication_NewView_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _BankApplication_Heartbeat_Handler,
		},
		{
			MethodName: "UpdateNodeStatus",
			Handler:    _BankApplication_UpdateNodeStatus_Handler,
		},
		{
			MethodName: "FailCurrentLeader",
			Handler:    _BankApplication_FailCurrentLeader_Handler,
		},
		{
			MethodName: "HandleClientRequest",
			Handler:    _BankApplication_HandleClientRequest_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _BankApplication_GetStatus_Handler,
		},
		{
			MethodName: "GetDB",
			Handler:    _BankApplication_GetDB_Handler,
		},
		{
			MethodName: "GetLog",
			Handler:    _BankApplication_GetLog_Handler,
		},
		{
			MethodName: "PrintView",
			Handler:    _BankApplication_PrintView_Handler,
		},
		{
			MethodName: "PrintLog",
			Handler:    _BankApplication_PrintLog_Handler,
		},
		{
			MethodName: "PrintBalance",
			Handler:    _BankApplication_PrintBalance_Handler,
		},
		{
			MethodName: "PerformActiveCatchUpAsFollower",
			Handler:    _BankApplication_PerformActiveCatchUpAsFollower_Handler,
		},
		{
			MethodName: "GetLeaderLogForActiveCatching",
			Handler:    _BankApplication_GetLeaderLogForActiveCatching_Handler,
		},
		{
			MethodName: "FlushPreviousDataAndUpdatePeersStatus",
			Handler:    _BankApplication_FlushPreviousDataAndUpdatePeersStatus_Handler,
		},
		{
			MethodName: "ReadClientBalance",
			Handler:    _BankApplication_ReadClientBalance_Handler,
		},
		{
			MethodName: "GetClusterLeader",
			Handler:    _BankApplication_GetClusterLeader_Handler,
		},
		{
			MethodName: "Prepare2PC",
			Handler:    _BankApplication_Prepare2PC_Handler,
		},
		{
			MethodName: "CommitOrAbort2PC",
			Handler:    _BankApplication_CommitOrAbort2PC_Handler,
		},
		{
			MethodName: "AcceptMessageFor2PCCommit",
			Handler:    _BankApplication_AcceptMessageFor2PCCommit_Handler,
		},
		{
			MethodName: "CommitMessageFor2PCCommit",
			Handler:    _BankApplication_CommitMessageFor2PCCommit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/paxos.proto",
}
